version: "3.8"
services:
  jaeger:
    container_name: jaeger
    hostname: jaeger
    image: jaegertracing/all-in-one:latest
    ports:
      - '16686:16686'
      - 4317:4317 
    networks:
      - external_network
  collector:
    container_name: collector
    hostname: collector
    image: otel/opentelemetry-collector:latest
    command: ['--config=/etc/otel-collector-config.yaml']
    volumes:
      - ./ca.crt:/ca.crt
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    networks:
      - external_network
    extra_hosts:
      - "apmserver-sample-apm-http:192.168.1.163"
  nginx:
    image: nginx-otel
    volumes:
      - ./opentelemetry_module.conf:/etc/nginx/conf.d/opentelemetry_module.conf
    ports:
      - 8080:80
    networks:
      - external_network
  # nginx:
  #   container_name: nginx
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #   restart: always
  #   environment:
  #     - LD_LIBRARY_PATH=/opt/opentelemetry-webserver-sdk/sdk_lib/lib
  #   ports:
  #     - 80:80
  #     - 443:443
  #   volumes:
  #     - ./opentelemetry_module.conf:/opt/opentelemetry-conf/opentelemetry_module.conf
  #     - ./ca.crt:/ca.crt
  #     - ./tls.crt:/tls.ctr
  #     - ./tls.key:/tls.key
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #     - ./default-certs:/etc/nginx/ssl
  #     - ./conf:/etc/nginx/conf.d
  #     - ./certbot/conf:/etc/nginx/ssl
  #     - ./letsencrypt:/etc/letsencrypt/
  #     - ./html:/var/www/html
  #   networks:
  #      - external_network
networks:
  external_network:
    driver: bridge

