receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors: 
  memory_limiter:
    check_interval: 1s
    limit_mib: 2000
  batch:

exporters:
  debug:
    verbosity: detailed 
  otlp/elastic: 
    # Elastic APM server https endpoint without the "https://" prefix
    endpoint: apmserver-sample-apm-http:8200 
    headers:
      # Elastic APM Server secret token
      Authorization: "Bearer 3me781m7zmfFc79VdX6T2xQ6"
    tls:
      #insecure: true
      #insecure_skip_verify: true
      ca_file: "./ca.crt" 
service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [debug, otlp/elastic]
    metrics:
      receivers: [otlp]
      exporters: [debug, otlp/elastic]
    logs: 
      receivers: [otlp]
      exporters: [debug, otlp/elastic]
